[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://www.campingpancakes.com/*"
  to = "https://campingpancakes.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.campingpancakes.com/*"
  to = "https://campingpancakes.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://campingpancakes.com/*"
  to = "https://campingpancakes.com/:splat"
  status = 301
  force = true
